spring:
  application:
    name: marisehat-api
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  logstash:
    server: logstash

domain:
  name: ${DOMAIN_NAME}

azure:
  activedirectory:
    client-secret: ${CLIENT_SECRET}
    tenant-id: ${TENANT_ID}
    client-id: ${CLIENT_ID}
    authorization-clients:
      graph:
        scopes: https://graph.microsoft.com/.default
    session-stateless: true
  storage:
    account-name: ${STORAGE_ACCOUNT_NAME}

springdoc:
  swagger-ui:
    oauth:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
      scopes: openid,api://marisehat/read,api://marisehat/write
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: ${OAUTH2_REDIRECT_URL}
  oAuthFlow:
    authorizationUrl: ${OAUTH2_AUTHORIZATION_URL}

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  config:
    azure:
      storage:
        endpoint: ${STORAGE_ENDPOINT}
        container-name: ${CONTAINER_NAME}
