spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

domain:
  name: ${DOMAIN_NAME}

azure:
  activedirectory:
    client-secret: ${CLIENT_SECRET}
    tenant-id: ${TENANT_ID}
    client-id: ${CLIENT_ID}
    authorization-clients:
      graph:
        scopes: https://graph.microsoft.com/.default
    session-stateless: true