name: CD

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/marisehat-api

    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Jar
        run: ./mvnw package -Dmaven.test.skip=true
        working-directory: marisehat

      - name: Build Docker Image
        run: docker build -t $APP_IMAGE .
        working-directory: marisehat

      - name: Push to Docker Hub
        run: docker push $APP_IMAGE  

      - uses: azure/webapps-deploy@v2
        with:
          app-name: marisehat
          images: ${{ secrets.DOCKERHUB_USERNAME }}/marisehat-api
